import {
  DriverLeaderboardEntry,
  LapRecord,
  StintData,
  WheelTelemetry,
  ConfoundingFactorBreakdown,
  StrategyOption,
  RaceEvent,
  ReportItem,
} from './types';

export interface CircuitInfo {
  id: string;
  name: string;
  location: string;
  country: string;
  lengthKm: number;
  totalLaps: number;
  totalDistanceKm: number;
  corners: number;
  nominalTrackTemp: number;
  nominalAirTemp: number;
  baseLapTimeSeconds: number;
  cliffLapThreshold: number;
}

export const CIRCUITS: Record<string, CircuitInfo> = {
  monza: {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    location: 'Monza, Italy',
    country: 'Italy',
    lengthKm: 5.793,
    totalLaps: 53,
    totalDistanceKm: 306.72,
    corners: 11,
    nominalTrackTemp: 39.4,
    nominalAirTemp: 24.2,
    baseLapTimeSeconds: 83.279, // 1:23.279
    cliffLapThreshold: 39.4,
  },
  silverstone: {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    location: 'Northamptonshire, UK',
    country: 'United Kingdom',
    lengthKm: 5.891,
    totalLaps: 52,
    totalDistanceKm: 306.19,
    corners: 18,
    nominalTrackTemp: 31.5,
    nominalAirTemp: 21.0,
    baseLapTimeSeconds: 88.54,
    cliffLapThreshold: 36.2,
  },
  spa: {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    location: 'Stavelot, Belgium',
    country: 'Belgium',
    lengthKm: 7.004,
    totalLaps: 44,
    totalDistanceKm: 308.05,
    corners: 19,
    nominalTrackTemp: 28.2,
    nominalAirTemp: 19.8,
    baseLapTimeSeconds: 104.52,
    cliffLapThreshold: 29.0,
  },
};

export const WHEEL_TELEMETRY_DATA: WheelTelemetry[] = [
  {
    corner: 'FL',
    label: 'FL // FRONT LEFT [C3 MEDIUM]',
    surfaceTemp: 104,
    carcassTemp: 99,
    pressure: 21.8,
    wearPercent: 72,
    status: 'MODERATE STRESS',
    grainingStatus: 'MINOR',
    blisterProbability: 14,
    tractionStatus: 'OPTIMAL',
  },
  {
    corner: 'FR',
    label: 'FR // FRONT RIGHT [C3 MEDIUM]',
    surfaceTemp: 108,
    carcassTemp: 105,
    pressure: 22.4,
    wearPercent: 76,
    status: 'THERMAL PEAK',
    grainingStatus: 'MODERATE',
    blisterProbability: 38,
    tractionStatus: 'DEGRADED',
  },
  {
    corner: 'RL',
    label: 'RL // REAR LEFT [C3 MEDIUM]',
    surfaceTemp: 98,
    carcassTemp: 95,
    pressure: 20.9,
    wearPercent: 64,
    status: 'NOMINAL',
    tractionStatus: 'OPTIMAL',
    grainingStatus: 'NONE',
    blisterProbability: 6,
  },
  {
    corner: 'RR',
    label: 'RR // REAR RIGHT [C3 MEDIUM]',
    surfaceTemp: 101,
    carcassTemp: 97,
    pressure: 21.1,
    wearPercent: 67,
    status: 'NOMINAL',
    tractionStatus: 'OPTIMAL',
    grainingStatus: 'NONE',
    blisterProbability: 9,
  },
];

export const CIRCUIT_DRIVERS: Record<string, DriverLeaderboardEntry[]> = {
  monza: [
    {
      position: 1,
      driverNumber: '16',
      driverCode: 'LEC',
      driverName: 'C. Leclerc',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 19,
      interval: 'LEADER',
      intervalSeconds: 0,
      lastLapTime: '1:21.432',
      lastLapSeconds: 81.432,
      degRatePerLap: 0.048,
      estPitWindow: 'L38-40',
      pitStatus: 'TRACK',
      isTargetDriver: true,
    },
    {
      position: 2,
      driverNumber: '81',
      driverCode: 'PIA',
      driverName: 'O. Piastri',
      team: 'McLaren',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 16,
      interval: '+2.664s',
      intervalSeconds: 2.664,
      lastLapTime: '1:21.650',
      lastLapSeconds: 81.65,
      degRatePerLap: 0.062,
      estPitWindow: 'L35-37',
      pitStatus: 'TRACK',
    },
    {
      position: 3,
      driverNumber: '04',
      driverCode: 'NOR',
      driverName: 'L. Norris',
      team: 'McLaren',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 16,
      interval: '+6.153s',
      intervalSeconds: 6.153,
      lastLapTime: '1:21.820',
      lastLapSeconds: 81.82,
      degRatePerLap: 0.065,
      estPitWindow: 'L34-36',
      pitStatus: 'TRACK',
    },
    {
      position: 4,
      driverNumber: '55',
      driverCode: 'SAI',
      driverName: 'C. Sainz',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 18,
      interval: '+15.621s',
      intervalSeconds: 15.621,
      lastLapTime: '1:22.110',
      lastLapSeconds: 82.11,
      degRatePerLap: 0.054,
      estPitWindow: 'L37-39',
      pitStatus: 'BOX WINDOW',
    },
    {
      position: 5,
      driverNumber: '44',
      driverCode: 'HAM',
      driverName: 'L. Hamilton',
      team: 'Mercedes-AMG',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 20,
      interval: '+22.820s',
      intervalSeconds: 22.82,
      lastLapTime: '1:22.340',
      lastLapSeconds: 82.34,
      degRatePerLap: 0.058,
      estPitWindow: 'L36-38',
      pitStatus: 'TRACK',
    },
    {
      position: 6,
      driverNumber: '01',
      driverCode: 'VER',
      driverName: 'M. Verstappen',
      team: 'Red Bull Racing',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: '+37.932s',
      intervalSeconds: 37.932,
      lastLapTime: '1:22.500',
      lastLapSeconds: 82.5,
      degRatePerLap: 0.06,
      estPitWindow: 'L40-42',
      pitStatus: 'TRACK',
    },
    {
      position: 7,
      driverNumber: '63',
      driverCode: 'RUS',
      driverName: 'G. Russell',
      team: 'Mercedes-AMG',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 17,
      interval: '+39.715s',
      intervalSeconds: 39.715,
      lastLapTime: '1:22.680',
      lastLapSeconds: 82.68,
      degRatePerLap: 0.064,
      estPitWindow: 'L36-38',
      pitStatus: 'TRACK',
    },
    {
      position: 8,
      driverNumber: '11',
      driverCode: 'PER',
      driverName: 'S. Perez',
      team: 'Red Bull Racing',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: '+54.148s',
      intervalSeconds: 54.148,
      lastLapTime: '1:22.920',
      lastLapSeconds: 82.92,
      degRatePerLap: 0.066,
      estPitWindow: 'L38-40',
      pitStatus: 'TRACK',
    },
    {
      position: 9,
      driverNumber: '23',
      driverCode: 'ALB',
      driverName: 'A. Albon',
      team: 'Williams Racing',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 21,
      interval: '+67.456s',
      intervalSeconds: 67.456,
      lastLapTime: '1:23.110',
      lastLapSeconds: 83.11,
      degRatePerLap: 0.052,
      estPitWindow: 'L39-41',
      pitStatus: 'TRACK',
    },
    {
      position: 10,
      driverNumber: '14',
      driverCode: 'ALO',
      driverName: 'F. Alonso',
      team: 'Aston Martin',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 14,
      interval: '+70.211s',
      intervalSeconds: 70.211,
      lastLapTime: '1:23.250',
      lastLapSeconds: 83.25,
      degRatePerLap: 0.07,
      estPitWindow: 'L35-37',
      pitStatus: 'TRACK',
    },
  ],
  silverstone: [
    {
      position: 1,
      driverNumber: '44',
      driverCode: 'HAM',
      driverName: 'L. Hamilton',
      team: 'Mercedes-AMG',
      compound: 'SOFT',
      compoundCode: 'C4',
      tyreAge: 12,
      interval: 'LEADER',
      intervalSeconds: 0,
      lastLapTime: '1:28.293',
      lastLapSeconds: 88.293,
      degRatePerLap: 0.075,
      estPitWindow: 'L38-40',
      pitStatus: 'TRACK',
      isTargetDriver: true,
    },
    {
      position: 2,
      driverNumber: '01',
      driverCode: 'VER',
      driverName: 'M. Verstappen',
      team: 'Red Bull Racing',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 14,
      interval: '+1.465s',
      intervalSeconds: 1.465,
      lastLapTime: '1:28.410',
      lastLapSeconds: 88.41,
      degRatePerLap: 0.045,
      estPitWindow: 'L36-38',
      pitStatus: 'TRACK',
    },
    {
      position: 3,
      driverNumber: '04',
      driverCode: 'NOR',
      driverName: 'L. Norris',
      team: 'McLaren',
      compound: 'SOFT',
      compoundCode: 'C4',
      tyreAge: 11,
      interval: '+7.514s',
      intervalSeconds: 7.514,
      lastLapTime: '1:28.620',
      lastLapSeconds: 88.62,
      degRatePerLap: 0.082,
      estPitWindow: 'L34-36',
      pitStatus: 'TRACK',
    },
    {
      position: 4,
      driverNumber: '81',
      driverCode: 'PIA',
      driverName: 'O. Piastri',
      team: 'McLaren',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 13,
      interval: '+12.429s',
      intervalSeconds: 12.429,
      lastLapTime: '1:28.580',
      lastLapSeconds: 88.58,
      degRatePerLap: 0.065,
      estPitWindow: 'L35-37',
      pitStatus: 'TRACK',
    },
    {
      position: 5,
      driverNumber: '55',
      driverCode: 'SAI',
      driverName: 'C. Sainz',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: '+47.318s',
      intervalSeconds: 47.318,
      lastLapTime: '1:28.910',
      lastLapSeconds: 88.91,
      degRatePerLap: 0.052,
      estPitWindow: 'L37-39',
      pitStatus: 'TRACK',
    },
    {
      position: 6,
      driverNumber: '27',
      driverCode: 'HUL',
      driverName: 'N. Hulkenberg',
      team: 'Haas F1 Team',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 16,
      interval: '+55.731s',
      intervalSeconds: 55.731,
      lastLapTime: '1:29.150',
      lastLapSeconds: 89.15,
      degRatePerLap: 0.055,
      estPitWindow: 'L38-40',
      pitStatus: 'TRACK',
    },
    {
      position: 7,
      driverNumber: '18',
      driverCode: 'STR',
      driverName: 'L. Stroll',
      team: 'Aston Martin',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 14,
      interval: '+57.699s',
      intervalSeconds: 57.699,
      lastLapTime: '1:29.340',
      lastLapSeconds: 89.34,
      degRatePerLap: 0.062,
      estPitWindow: 'L36-38',
      pitStatus: 'TRACK',
    },
    {
      position: 8,
      driverNumber: '14',
      driverCode: 'ALO',
      driverName: 'F. Alonso',
      team: 'Aston Martin',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 14,
      interval: '+60.577s',
      intervalSeconds: 60.577,
      lastLapTime: '1:29.410',
      lastLapSeconds: 89.41,
      degRatePerLap: 0.064,
      estPitWindow: 'L36-38',
      pitStatus: 'TRACK',
    },
    {
      position: 9,
      driverNumber: '23',
      driverCode: 'ALB',
      driverName: 'A. Albon',
      team: 'Williams Racing',
      compound: 'MEDIUM',
      compoundCode: 'C3',
      tyreAge: 15,
      interval: '+68.387s',
      intervalSeconds: 68.387,
      lastLapTime: '1:29.620',
      lastLapSeconds: 89.62,
      degRatePerLap: 0.06,
      estPitWindow: 'L37-39',
      pitStatus: 'TRACK',
    },
    {
      position: 10,
      driverNumber: '16',
      driverCode: 'LEC',
      driverName: 'C. Leclerc',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 13,
      interval: '+74.210s',
      intervalSeconds: 74.21,
      lastLapTime: '1:29.800',
      lastLapSeconds: 89.8,
      degRatePerLap: 0.058,
      estPitWindow: 'L35-37',
      pitStatus: 'TRACK',
    },
  ],
  spa: [
    {
      position: 1,
      driverNumber: '44',
      driverCode: 'HAM',
      driverName: 'L. Hamilton',
      team: 'Mercedes-AMG',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: 'LEADER',
      intervalSeconds: 0,
      lastLapTime: '1:44.750',
      lastLapSeconds: 104.75,
      degRatePerLap: 0.05,
      estPitWindow: 'L30-32',
      pitStatus: 'TRACK',
    },
    {
      position: 2,
      driverNumber: '81',
      driverCode: 'PIA',
      driverName: 'O. Piastri',
      team: 'McLaren',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 13,
      interval: '+0.647s',
      intervalSeconds: 0.647,
      lastLapTime: '1:44.520',
      lastLapSeconds: 104.52,
      degRatePerLap: 0.048,
      estPitWindow: 'L31-33',
      pitStatus: 'TRACK',
    },
    {
      position: 3,
      driverNumber: '16',
      driverCode: 'LEC',
      driverName: 'C. Leclerc',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 14,
      interval: '+8.023s',
      intervalSeconds: 8.023,
      lastLapTime: '1:44.910',
      lastLapSeconds: 104.91,
      degRatePerLap: 0.055,
      estPitWindow: 'L29-31',
      pitStatus: 'TRACK',
      isTargetDriver: true,
    },
    {
      position: 4,
      driverNumber: '01',
      driverCode: 'VER',
      driverName: 'M. Verstappen',
      team: 'Red Bull Racing',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: '+8.700s',
      intervalSeconds: 8.7,
      lastLapTime: '1:44.880',
      lastLapSeconds: 104.88,
      degRatePerLap: 0.052,
      estPitWindow: 'L30-32',
      pitStatus: 'TRACK',
    },
    {
      position: 5,
      driverNumber: '04',
      driverCode: 'NOR',
      driverName: 'L. Norris',
      team: 'McLaren',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 15,
      interval: '+9.324s',
      intervalSeconds: 9.324,
      lastLapTime: '1:44.890',
      lastLapSeconds: 104.89,
      degRatePerLap: 0.051,
      estPitWindow: 'L30-32',
      pitStatus: 'TRACK',
    },
    {
      position: 6,
      driverNumber: '55',
      driverCode: 'SAI',
      driverName: 'C. Sainz',
      team: 'Scuderia Ferrari',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 16,
      interval: '+19.269s',
      intervalSeconds: 19.269,
      lastLapTime: '1:45.120',
      lastLapSeconds: 105.12,
      degRatePerLap: 0.056,
      estPitWindow: 'L28-30',
      pitStatus: 'TRACK',
    },
    {
      position: 7,
      driverNumber: '11',
      driverCode: 'PER',
      driverName: 'S. Perez',
      team: 'Red Bull Racing',
      compound: 'SOFT',
      compoundCode: 'C4',
      tyreAge: 8,
      interval: '+42.663s',
      intervalSeconds: 42.663,
      lastLapTime: '1:44.701',
      lastLapSeconds: 104.701,
      degRatePerLap: 0.088,
      estPitWindow: 'L35-37',
      pitStatus: 'TRACK',
    },
    {
      position: 8,
      driverNumber: '14',
      driverCode: 'ALO',
      driverName: 'F. Alonso',
      team: 'Aston Martin',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 17,
      interval: '+49.437s',
      intervalSeconds: 49.437,
      lastLapTime: '1:45.450',
      lastLapSeconds: 105.45,
      degRatePerLap: 0.054,
      estPitWindow: 'L29-31',
      pitStatus: 'TRACK',
    },
    {
      position: 9,
      driverNumber: '31',
      driverCode: 'OCO',
      driverName: 'E. Ocon',
      team: 'Alpine F1 Team',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 14,
      interval: '+52.026s',
      intervalSeconds: 52.026,
      lastLapTime: '1:45.610',
      lastLapSeconds: 105.61,
      degRatePerLap: 0.058,
      estPitWindow: 'L30-32',
      pitStatus: 'TRACK',
    },
    {
      position: 10,
      driverNumber: '03',
      driverCode: 'RIC',
      driverName: 'D. Ricciardo',
      team: 'Visa Cash App RB',
      compound: 'HARD',
      compoundCode: 'C2',
      tyreAge: 13,
      interval: '+54.400s',
      intervalSeconds: 54.4,
      lastLapTime: '1:45.720',
      lastLapSeconds: 105.72,
      degRatePerLap: 0.059,
      estPitWindow: 'L29-31',
      pitStatus: 'TRACK',
    },
  ],
};

export const DRIVERS_GRID: DriverLeaderboardEntry[] = CIRCUIT_DRIVERS.monza;

export function getCircuitDrivers(circuitId: string): DriverLeaderboardEntry[] {
  const cid = (circuitId || 'monza').toLowerCase();
  return CIRCUIT_DRIVERS[cid] || CIRCUIT_DRIVERS.monza;
}

export const STINTS_DATA: StintData[] = [
  {
    stintNumber: 1,
    compound: 'SOFT',
    compoundCode: 'C4',
    startLap: 1,
    endLap: 16,
    totalLaps: 16,
    avgPace: '1:24.612s',
    avgPaceSeconds: 84.612,
    bestLap: '1:23.420s',
    worstLap: '1:26.110s',
    degRate: 0.114,
    pitLossSeconds: 21.82,
    status: 'COMPLETED',
    tyreTerminalState: 'Scrubbed + Severe Thermal Cliff (L14-16)',
    fuelCorrectedDeltaVsBaseline: 0.84,
    thermalStabilityIndex: 62,
  },
  {
    stintNumber: 2,
    compound: 'MEDIUM',
    compoundCode: 'C3',
    startLap: 17,
    endLap: 34,
    totalLaps: 18,
    avgPace: '1:23.842s',
    avgPaceSeconds: 83.842,
    bestLap: '1:23.218s',
    worstLap: '1:24.510s',
    degRate: 0.078,
    pitLossSeconds: 21.41,
    status: 'ACTIVE',
    tyreTerminalState: 'Optimal Wear Retention, Accelerated FR Heating',
    fuelCorrectedDeltaVsBaseline: -0.77,
    thermalStabilityIndex: 89,
  },
  {
    stintNumber: 3,
    compound: 'HARD',
    compoundCode: 'C2',
    startLap: 38,
    endLap: 53,
    totalLaps: 15,
    avgPace: '1:23.640s (PROJ)',
    avgPaceSeconds: 83.64,
    bestLap: '1:23.100s',
    worstLap: '1:24.080s',
    degRate: 0.042,
    pitLossSeconds: 21.4,
    status: 'PROJECTED',
    tyreTerminalState: 'Ultra Stable C2 Spec, Projected Linear Degradation',
    fuelCorrectedDeltaVsBaseline: -1.24,
    thermalStabilityIndex: 95,
  },
];

export const CIRCUIT_CONFOUNDING_FACTORS: Record<string, ConfoundingFactorBreakdown[]> = {
  monza: [
    {
      id: 'factor-1',
      name: '1. TYRE AGE (PRIMARY FACTOR)',
      category: 'TYRE_AGE',
      impactLabel: 'CRITICAL TRACTION WEAR',
      impactValueStr: '+0.052 s/lap',
      impactValueSeconds: 0.052,
      direction: 'Longitudinal braking wear',
      sharePercentage: 31.2,
      description:
        'Mechanical tyre wear at Monza is primarily longitudinal, driven by heavy 350+ km/h deceleration zones into Prima Variante, Roggia, and Ascari chicane.',
      severity: 'HIGH',
    },
    {
      id: 'factor-2',
      name: '2. TRACK EVOLUTION',
      category: 'TRACK_EVO',
      impactLabel: 'MODERATE IMPACT',
      impactValueStr: '+0.026 s/lap gain',
      impactValueSeconds: -0.026,
      direction: 'Compensating / Faster',
      sharePercentage: 22.4,
      description:
        'Moderate rubber deposition along Curva Grande and Lesmo turns; lower aerodynamic downforce reduces relative rubber compaction vs high-downforce tracks.',
      severity: 'MEDIUM',
    },
    {
      id: 'factor-3',
      name: '3. TRAFFIC & DIRTY AIR',
      category: 'TRAFFIC',
      impactLabel: 'ELEVATED SLIPSTREAM',
      impactValueStr: '+0.410 s delta',
      impactValueSeconds: 0.41,
      direction: 'Aerodynamic wake / Brake thermal spike',
      sharePercentage: 14.6,
      description:
        'While DRS provides straightline slipstream, trailing in dirty air causes severe front tyre understeer and front brake overheating into Turn 1.',
      severity: 'HIGH',
    },
    {
      id: 'factor-4',
      name: '4. FUEL LOAD PROXY',
      category: 'FUEL_MASS',
      impactLabel: 'HIGH SPEEDUP IMPACT',
      impactValueStr: '-0.0642 s/lap',
      impactValueSeconds: -0.0642,
      direction: 'Straightline mass reduction',
      sharePercentage: 27.8,
      description:
        'High sensitivity to fuel burn on Monza long straights; burning 1.72 kg/lap yields ~0.064s gain as acceleration out of low-speed chicanes improves.',
      severity: 'HIGH',
    },
    {
      id: 'factor-5',
      name: '5. SURFACE THERMAL GRADIENT',
      category: 'THERMAL_STRESS',
      impactLabel: 'BRAKING SPIKE STRESS',
      impactValueStr: '+0.014 s thermal wear',
      impactValueSeconds: 0.014,
      direction: 'Thermal brake-to-rim conduction',
      sharePercentage: 16.5,
      description:
        'High-speed straights cool tyre tread surfaces, but heavy chicane braking conducts intense heat from carbon discs into the wheel rims and carcass.',
      severity: 'MEDIUM',
    },
  ],
  silverstone: [
    {
      id: 'factor-1',
      name: '1. TYRE AGE (PRIMARY FACTOR)',
      category: 'TYRE_AGE',
      impactLabel: 'CRITICAL LATERAL LOAD',
      impactValueStr: '+0.096 s/lap',
      impactValueSeconds: 0.096,
      direction: 'Extreme lateral abrasion',
      sharePercentage: 42.8,
      description:
        'Violent lateral energy through Copse, Maggotts, Becketts, and Stowe shears polymer bonds on the Front-Left tyre, causing severe rapid degradation.',
      severity: 'CRITICAL',
    },
    {
      id: 'factor-2',
      name: '2. TRACK EVOLUTION',
      category: 'TRACK_EVO',
      impactLabel: 'HIGH IMPACT',
      impactValueStr: '+0.044 s/lap gain',
      impactValueSeconds: -0.044,
      direction: 'Compensating / Faster',
      sharePercentage: 31.5,
      description:
        'High aerodynamic downforce grinds Pirelli rubber deep into the coarse Northamptonshire asphalt, yielding a massive grip evolution of +0.044s/lap.',
      severity: 'HIGH',
    },
    {
      id: 'factor-3',
      name: '3. TRAFFIC & DIRTY AIR',
      category: 'TRAFFIC',
      impactLabel: 'CRITICAL WAKE LOSS',
      impactValueStr: '+0.480 s delta',
      impactValueSeconds: 0.48,
      direction: 'High-speed aero wash & graining',
      sharePercentage: 9.4,
      description:
        'Trailing within 1.5s through Maggotts-Becketts causes catastrophic loss of front downforce, leading to front-axle sliding and instantaneous blistering.',
      severity: 'CRITICAL',
    },
    {
      id: 'factor-4',
      name: '4. FUEL LOAD PROXY',
      category: 'FUEL_MASS',
      impactLabel: 'MODERATE IMPACT',
      impactValueStr: '-0.0540 s/lap',
      impactValueSeconds: -0.054,
      direction: 'Directional change agility',
      sharePercentage: 18.2,
      description:
        'Mass reduction of 1.68 kg/lap primarily assists high-speed chassis responsiveness during rapid left-right direction transitions through Becketts.',
      severity: 'MEDIUM',
    },
    {
      id: 'factor-5',
      name: '5. SURFACE THERMAL GRADIENT',
      category: 'THERMAL_STRESS',
      impactLabel: 'CONTINUOUS CORE HEATING',
      impactValueStr: '+0.024 s thermal wear',
      impactValueSeconds: 0.024,
      direction: 'High-energy lateral hysteresis',
      sharePercentage: 24.6,
      description:
        'Sustained lateral 5G cornering loads drive internal carcass temperatures past 112°C, accelerating thermal degradation and sub-surface blister risk.',
      severity: 'HIGH',
    },
  ],
  spa: [
    {
      id: 'factor-1',
      name: '1. TYRE AGE (PRIMARY FACTOR)',
      category: 'TYRE_AGE',
      impactLabel: 'HIGH COMPRESSION WEAR',
      impactValueStr: '+0.088 s/lap',
      impactValueSeconds: 0.088,
      direction: 'Vertical compression & Pouhon shear',
      sharePercentage: 38.6,
      description:
        'Extreme vertical compression through Eau Rouge & Raidillon followed by prolonged high-speed lateral loading in Pouhon drives heavy tread degradation.',
      severity: 'HIGH',
    },
    {
      id: 'factor-2',
      name: '2. TRACK EVOLUTION',
      category: 'TRACK_EVO',
      impactLabel: 'HIGH IMPACT',
      impactValueStr: '+0.036 s/lap gain',
      impactValueSeconds: -0.036,
      direction: 'Compensating / Faster',
      sharePercentage: 26.2,
      description:
        'Continuous rubber deposition across the 7.004 km layout from La Source to the Bus Stop chicane steadily enhances mechanical grip as session matures.',
      severity: 'HIGH',
    },
    {
      id: 'factor-3',
      name: '3. TRAFFIC & DIRTY AIR',
      category: 'TRAFFIC',
      impactLabel: 'SECTOR 2 DIRTY AIR',
      impactValueStr: '+0.370 s delta',
      impactValueSeconds: 0.37,
      direction: 'Kemmel slipstream vs S2 loss',
      sharePercentage: 7.8,
      description:
        'Massive slipstream gains down Kemmel Straight are offset by dirty air wash throughout the twisty downhill sequence from Bruxelles to Stavelot.',
      severity: 'MEDIUM',
    },
    {
      id: 'factor-4',
      name: '4. FUEL LOAD PROXY',
      category: 'FUEL_MASS',
      impactLabel: 'ELEVATED IMPACT (7KM LAP)',
      impactValueStr: '-0.0581 s/lap',
      impactValueSeconds: -0.0581,
      direction: 'Elevation burn-off speedup',
      sharePercentage: 21.5,
      description:
        'Burning ~2.1 kg of fuel per 7 km lap delivers substantial lap-over-lap pace gains as the car sheds weight climbing 102 meters of Ardennes elevation.',
      severity: 'HIGH',
    },
    {
      id: 'factor-5',
      name: '5. SURFACE THERMAL GRADIENT',
      category: 'THERMAL_STRESS',
      impactLabel: 'MICRO-CLIMATE FLUCTUATION',
      impactValueStr: '+0.021 s thermal wear',
      impactValueSeconds: 0.021,
      direction: 'Ardennes forest micro-climate gradient',
      sharePercentage: 21.0,
      description:
        'Asphalt temperature varies up to 5°C between exposed pit straights and tree-shaded valley sections, creating cyclical thermal expansion in tyre rubber.',
      severity: 'HIGH',
    },
  ],
};

export function getCircuitConfoundingFactors(circuitId: string): ConfoundingFactorBreakdown[] {
  return CIRCUIT_CONFOUNDING_FACTORS[circuitId] || CIRCUIT_CONFOUNDING_FACTORS['monza'];
}

export const CONFOUNDING_FACTORS: ConfoundingFactorBreakdown[] = CIRCUIT_CONFOUNDING_FACTORS['monza'];

export const STRATEGY_OPTIONS: StrategyOption[] = [
  {
    id: 'A',
    codeName: 'STRATEGY A [1-STOP OPTIMAL]',
    title: 'Plan A: Box Lap 37-39 (Medium -> Hard)',
    isRecommended: true,
    type: '1-STOP',
    sequenceStr: 'MEDIUM (C3) -> HARD (C2)',
    stints: [
      { compound: 'MEDIUM', compoundCode: 'C3', startLap: 1, endLap: 38, laps: 38, note: 'L17-38 Stint 2 (22 Laps)' },
      { compound: 'HARD', compoundCode: 'C2', startLap: 39, endLap: 53, laps: 15, note: 'Sprint to flag' },
    ],
    pitWindow: 'L37 - L39',
    targetPitLap: 38,
    netDeltaSeconds: -2.8,
    deltaVsBenchmarkStr: '-2.8s vs Staying Out (Clear Air)',
    confidencePercent: 87,
    estTotalRaceTime: '1:16:42.8',
    reentryTraffic: '92% CLEAR AIR',
    reentryPosition: 'P4 (+4.2s ahead of P5)',
    reentryBufferStr: '+4.2s Buffer in Clean Air',
    riskFactor: 'Low • Defends position against P5 undercut',
    description:
      'Current C3 Medium degradation is accelerating (+0.078s/lap). Front-Right tire temperature peaks at 108°C. Model forecasts thermal cliff at Lap 39.5. Pitting on Lap 38 secures track position against the P5 undercut (+11.2s gap) and fits fresh C2 Hards with negligible degradation (+0.042s/lap).',
  },
  {
    id: 'B',
    codeName: 'STRATEGY B [LONG OVERCUT]',
    title: 'Plan B: Extend to Lap 40-42 (Medium -> Hard)',
    isRecommended: false,
    type: 'OVERCUT',
    sequenceStr: 'MEDIUM (C3) -> HARD (C2)',
    stints: [
      { compound: 'MEDIUM', compoundCode: 'C3', startLap: 1, endLap: 41, laps: 41, note: 'Cliff exposure L39-41' },
      { compound: 'HARD', compoundCode: 'C2', startLap: 42, endLap: 53, laps: 12, note: 'Short sprint' },
    ],
    pitWindow: 'L40 - L42',
    targetPitLap: 41,
    netDeltaSeconds: 1.3,
    deltaVsBenchmarkStr: '+1.3s Deficit vs Plan A',
    confidencePercent: 84,
    estTotalRaceTime: '1:16:44.1',
    reentryTraffic: '78% CLEAR (22% TRAFFIC RISK)',
    reentryPosition: 'P5 (Behind rival car if undercut succeeds)',
    reentryBufferStr: '-1.1s Behind rival on exit',
    riskFactor: 'Moderate • Severe tyre cliff penalty of ~1.2s/lap past L39.4',
    description:
      'Gambles on a Safety Car or VSC neutralization between L39 and L42. High risk of severe graining cliff costing >1.2s per lap from L39 onwards. Re-enters dangerously close to traffic train.',
  },
  {
    id: 'C',
    codeName: 'STRATEGY C [2-STOP ATTACK SPRINT]',
    title: 'Plan C: Aggressive 2-Stop (Medium -> Soft -> Hard)',
    isRecommended: false,
    type: '2-STOP',
    sequenceStr: 'MEDIUM (C3) -> SOFT (C4) -> HARD (C2)',
    stints: [
      { compound: 'MEDIUM', compoundCode: 'C3', startLap: 1, endLap: 36, laps: 36, note: 'Box L36' },
      { compound: 'SOFT', compoundCode: 'C4', startLap: 37, endLap: 46, laps: 10, note: 'Max attack sprint' },
      { compound: 'HARD', compoundCode: 'C2', startLap: 47, endLap: 53, laps: 7, note: 'Final sprint' },
    ],
    pitWindow: 'L36 & L47',
    targetPitLap: 36,
    netDeltaSeconds: 4.4,
    deltaVsBenchmarkStr: '+4.4s Deficit vs Plan A',
    confidencePercent: 76,
    estTotalRaceTime: '1:16:47.2',
    reentryTraffic: '45% CLEAR (HEAVY DIRTY AIR)',
    reentryPosition: 'P7 (Requires 2 overtakes on track)',
    reentryBufferStr: 'Trapped in mid-pack traffic',
    riskFactor: 'High • Additional 21.4s pit loss transit penalty',
    description:
      'Double pit stop inflicts an additional 21.4s pit lane loss. Even with the raw +0.9s pace advantage of Soft C4 tyres, overtaking deltas at Monza require at least +1.2s delta in dirty air, resulting in negative net race equity.',
  },
];

export const HISTORICAL_LAPS: LapRecord[] = Array.from({ length: 53 }, (_, i) => {
  const lap = i + 1;
  const isPast = lap <= 34;

  let compound: 'SOFT' | 'MEDIUM' | 'HARD' = 'MEDIUM';
  let tyreAge = lap - 16;
  if (lap <= 16) {
    compound = 'SOFT';
    tyreAge = lap;
  } else if (lap > 38) {
    compound = 'HARD';
    tyreAge = lap - 38;
  }

  // Physics-based decomposition:
  const baseLapTime = 83.279; // 1:23.279
  const fuelOffset = -0.0581 * lap; // gaining ~0.058s per lap as fuel burns
  const trackGripOffset = -0.025 * Math.log(lap + 1); // track rubbers in

  let trueWearDelta = 0;
  if (compound === 'SOFT') {
    trueWearDelta = 0.04 * tyreAge + (tyreAge > 12 ? 0.08 * (tyreAge - 12) ** 1.6 : 0);
  } else if (compound === 'MEDIUM') {
    // Cliff after age 22 (around lap 38-39)
    trueWearDelta = 0.032 * tyreAge + (tyreAge > 22 ? 0.09 * (tyreAge - 22) ** 1.8 : 0);
  } else {
    trueWearDelta = 0.02 * tyreAge;
  }

  // In dirty air between lap 20-25
  const trafficOffset = lap >= 21 && lap <= 24 ? 0.38 : 0;
  const observedDelta = trueWearDelta + fuelOffset + trackGripOffset + trafficOffset;
  const modelPredictedDelta = trueWearDelta + fuelOffset + trackGripOffset;

  const lapSeconds = baseLapTime + (isPast ? observedDelta : modelPredictedDelta);
  const minutes = Math.floor(lapSeconds / 60);
  const remSec = (lapSeconds % 60).toFixed(3);
  const lapTimeStr = `${minutes}:${remSec.padStart(6, '0')}`;

  const inPitWindow = lap >= 37 && lap <= 39;

  return {
    lapNumber: lap,
    lapTimeStr,
    lapTimeSeconds: Number(lapSeconds.toFixed(3)),
    s1: Number((26.812 + (lap % 3) * 0.04).toFixed(3)),
    s2: Number((26.94 + (lap % 4) * 0.03).toFixed(3)),
    s3: Number((29.66 + (lap % 2) * 0.05).toFixed(3)),
    compound,
    tyreAge,
    observedDelta: Number(observedDelta.toFixed(3)),
    modelPredictedDelta: Number(modelPredictedDelta.toFixed(3)),
    trueWearDelta: Number(trueWearDelta.toFixed(3)),
    fuelOffset: Number(fuelOffset.toFixed(3)),
    trackGripOffset: Number(trackGripOffset.toFixed(3)),
    trafficOffset: Number(trafficOffset.toFixed(3)),
    trackTemp: Number((39.4 + Math.sin(lap / 10) * 0.4).toFixed(1)),
    airTemp: 24.2,
    flag: lap === 14 ? 'VSC' : 'GREEN',
    inPitWindow,
  };
});

export const RACE_EVENTS_LOG: RaceEvent[] = [
  {
    id: 'ev-1',
    lap: 34,
    timeStr: '14:32:18',
    type: 'PIT_TRIGGER',
    title: 'PIT WINDOW ARMED // PLAN A ACTIVATED',
    details: 'Telemetry triggers strategic pit window L37-39. Re-entry gap +4.2s ahead of P5 projected in clear air.',
    severity: 'SUCCESS',
  },
  {
    id: 'ev-2',
    lap: 31,
    timeStr: '14:27:44',
    type: 'THERMAL_PEAK',
    title: 'FRONT RIGHT THERMAL ELEVATION (108°C)',
    details: 'FR pyrometer crosses 105°C threshold in Curva Grande. Surface blistering risk elevated to 38%.',
    severity: 'WARNING',
  },
  {
    id: 'ev-3',
    lap: 28,
    timeStr: '14:23:10',
    type: 'GRAINING',
    title: 'COMPETITOR TIMING: P5 TRACK INTERVAL',
    details: 'Chasing car reporting front-left graining and braking instability into Variante Ascari.',
    severity: 'INFO',
  },
  {
    id: 'ev-4',
    lap: 24,
    timeStr: '14:17:05',
    type: 'TRAFFIC',
    title: 'CLEAN AIR RESTORED (+3.8s GAP)',
    details: 'Traffic train cleared past backmarkers. Aerodynamic turbulent wake decoupled from timing stream.',
    severity: 'SUCCESS',
  },
  {
    id: 'ev-5',
    lap: 16,
    timeStr: '14:06:22',
    type: 'PIT_STOP',
    title: 'STINT 1 COMPLETED // PIT STOP EXECUTED',
    details: 'Stationary pit stop: 2.38s. Total pit lane transit: 21.82s. Switched from C4 Soft to C3 Medium.',
    severity: 'INFO',
  },
  {
    id: 'ev-6',
    lap: 14,
    timeStr: '14:03:50',
    type: 'FLAG',
    title: 'VIRTUAL SAFETY CAR ENDED',
    details: 'Debris cleared from Variante del Rettifilo. Normal racing speeds resumed.',
    severity: 'INFO',
  },
];

export const AUDIT_REPORTS: ReportItem[] = [
  {
    id: 'rpt-1',
    reportCode: '#RPT-MNZ-0926-01',
    title: 'MONZA GP 2026 // FULL RACE STRATEGY & TYRE DOSSIER',
    grandPrix: 'Monza Grand Prix',
    circuit: 'Autodromo Nazionale Monza',
    session: 'Race Session (53 Laps)',
    driver: 'C. Leclerc',
    driverNumber: '#16',
    type: 'FULL_RACE',
    dateStr: '2026-09-06 15:45 UTC',
    status: 'READY',
    recommendedPitWindow: 'LAP 37 - 39',
    estDegradation: '+0.087 s/lap',
    confidence: 87,
    netRaceTimeGain: '+2.8 SEC',
    summary:
      'TrueWear automated race strategy report decoupling confounding fuel load (-0.058s/lap) and track evolution (+0.038s/lap) from mechanical tyre wear. Recommends a targeted 1-stop strategy switching to C2 Hard at Lap 38.',
    sections: {
      tyreAnalysis: {
        wearRate: '0.024 mm/lap (FR Accelerated)',
        thermalHysteresis: 'Elevated in Curva Grande & Lesmos',
        blisteringIndex: '12.4% (Below 25% Critical)',
        carcassCoreTemp: '105°C (Front Right Peak)',
      },
      strategyAnalysis: {
        undercutVulnerability: 'PROTECTED (+11.2s vs P5)',
        overcutDelta: '+1.4s Deficit if extended beyond L40',
        trafficExitCleanAir: '88% Probability of clean air entry',
        expectedPositionReentry: 'P4 (+4.2s cushion)',
      },
      trackConditions: {
        surfaceGripEvolution: '+4.2% Total session grip gain',
        trackTempDelta: '39.4°C (Stabilized within ±0.3°C)',
        rubberingIn: '1.042μ Asphalt friction coefficient',
        wind: '11.4 km/h NE with 16 km/h gusts at Ascari',
      },
      modelPerformance: {
        mae: '0.084s (Target passed <0.100s)',
        rmse: '0.117s (Stint normalized)',
        fiaSync: 'Verified FastF1 Public Data',
        inferenceLatency: '< 10ms (Real-time edge ready)',
      },
    },
  },
  {
    id: 'rpt-2',
    reportCode: '#RPT-MNZ-0926-02',
    title: 'STINT 2 C3 MEDIUM DEGRADATION VELOCITY PROFILE',
    grandPrix: 'Monza Grand Prix',
    circuit: 'Autodromo Nazionale Monza',
    session: 'Race Session (Laps 17-34)',
    driver: 'C. Leclerc',
    driverNumber: '#16',
    type: 'TYRE_DEG',
    dateStr: '2026-09-06 14:35 UTC',
    status: 'READY',
    recommendedPitWindow: 'LAP 38',
    estDegradation: '+0.078 s/lap',
    confidence: 91,
    netRaceTimeGain: '+1.9 SEC',
    summary:
      'High-resolution pyrometer and wheel sensor analysis tracking thermal acceleration across Stint 2. Identifies upcoming graining cliff at Lap 39.4.',
    sections: {
      tyreAnalysis: {
        wearRate: '0.021 mm/lap (Tread Depth 2.8mm remaining)',
        thermalHysteresis: 'Front-Right thermal asymmetry +4°C',
        blisteringIndex: '38% peak on outer shoulder',
        carcassCoreTemp: '105°C',
      },
      strategyAnalysis: {
        undercutVulnerability: 'LOW',
        overcutDelta: '+1.3s',
        trafficExitCleanAir: '92% probability',
        expectedPositionReentry: 'P4',
      },
      trackConditions: {
        surfaceGripEvolution: '+0.0024 index/lap',
        trackTempDelta: '39.4°C peak',
        rubberingIn: '1.042μ',
        wind: '11.4 km/h NE',
      },
      modelPerformance: {
        mae: '0.079s',
        rmse: '0.109s',
        fiaSync: 'Verified',
        inferenceLatency: '3.8ms',
      },
    },
  },
  {
    id: 'rpt-3',
    reportCode: '#RPT-SIL-0726-04',
    title: 'SILVERSTONE GP 2026 // MULTI-COMPOUND HISTORICAL AUDIT',
    grandPrix: 'Silverstone Circuit',
    circuit: 'Silverstone Circuit',
    session: 'Race Session (52 Laps)',
    driver: 'L. Hamilton',
    driverNumber: '#44',
    type: 'STRATEGY',
    dateStr: '2026-07-12 16:10 UTC',
    status: 'ARCHIVED',
    recommendedPitWindow: 'LAP 18 & LAP 36',
    estDegradation: '+0.112 s/lap',
    confidence: 89,
    netRaceTimeGain: '+4.1 SEC',
    summary:
      'Archived high-energy lateral tyre stress benchmark at Copse, Maggotts, and Becketts corners comparing C1 and C2 compound degradation.',
    sections: {
      tyreAnalysis: {
        wearRate: '0.038 mm/lap',
        thermalHysteresis: 'Severe lateral shoulder stress',
        blisteringIndex: '28.1%',
        carcassCoreTemp: '112°C',
      },
      strategyAnalysis: {
        undercutVulnerability: 'HIGH (2.4s undercut delta)',
        overcutDelta: '-0.8s',
        trafficExitCleanAir: '65%',
        expectedPositionReentry: 'P3',
      },
      trackConditions: {
        surfaceGripEvolution: '+2.8%',
        trackTempDelta: '31.5°C',
        rubberingIn: '1.018μ',
        wind: '18.2 km/h SW',
      },
      modelPerformance: {
        mae: '0.091s',
        rmse: '0.124s',
        fiaSync: 'Verified',
        inferenceLatency: '4.5ms',
      },
    },
  },
];

export const FIRESTORE_COLLECTIONS_METRICS = [
  { name: 'race_sessions', docsCount: 12, sizeStr: '18.4 MB', description: 'Session telemetry, flags, and circuit baselines' },
  { name: 'processed_features', docsCount: 340500, sizeStr: '840.2 MB', description: '36 engineered ML signals and telemetry features' },
  { name: 'predictions', docsCount: 2480, sizeStr: '4.1 MB', description: '95% confidence intervals and degradation slopes' },
  { name: 'strategies', docsCount: 640, sizeStr: '12.8 MB', description: 'Monte Carlo simulation race permutations' },
  { name: 'user_sessions', docsCount: 8, sizeStr: '64.0 KB', description: 'Race engineer client instances and audit logs' },
];
